### ISSUE TITLE
Yo dude you removed me again!

### ISSUE THREAD

**Issue by Lolovcek** [InferNovac/simon-says#1]
Hi, you removed me again from discord :( Is there a reason for it or did you just like missclick?

**Comment by InferNovac** [comment]
Sowie I was deep cleaning friends list with a script so. It can delete to many by accident.

**Comment by Lolovcek** [comment]
Well don't run the script then and don't add everyone :D I almost had no way of contacting you dude :D And my friend who you are working with was texting me about it.
